AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - app/views/**/*
    - config/**/*
    - db/**/**
    - vendor/**/*
    - bin/**/*
    - lib/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - spec/**/*
    - config.ru
    - Guardfile
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - Readme.md
